project_name: sqly
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
    - go mod tidy
builds:
  - id: darwin-amd64
    binary: sqly
    ldflags:
      - -s -w -X 'github.com/nao1215/sqly/config.Version=v{{ .Version }}'
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    main: .
    goos:
      - darwin
    goarch:
      - amd64
  - id: linux-amd64
    binary: sqly
    env:
      - CGO_ENABLED=1
    main: .
    ldflags:
      - -extldflags "-static"
      - -s -w -X 'github.com/nao1215/sqly/config.Version=v{{ .Version }}'
    goos:
      - linux
    goarch:
      - amd64
  - id: windows-amd64
    binary: sqly
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    main: .
    ldflags:
      - -H=windowsgui
      - -extldflags "-static"
      - -s -w -X 'github.com/nao1215/sqly/config.Version=v{{ .Version }}'
    goos:
      - windows
    goarch:
      - amd64
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
nfpms:
  - maintainer: Naohiro CHIKAMATSU <n.chika156@gmail.com>
    description: sqly - execute SQL against CSV / JSON with shell.
    homepage: https://github.com/nao1215/sqly
    license: MIT License
    formats:
      - deb
      - rpm
      - apk
