// Code generated by MockGen. DO NOT EDIT.
// Source: history.go
//
// Generated by this command:
//
//	mockgen -typed -source=history.go -destination=../../infrastructure/mock/history.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/nao1215/sqly/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockHistoryRepository is a mock of HistoryRepository interface.
type MockHistoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockHistoryRepositoryMockRecorder
	isgomock struct{}
}

// MockHistoryRepositoryMockRecorder is the mock recorder for MockHistoryRepository.
type MockHistoryRepositoryMockRecorder struct {
	mock *MockHistoryRepository
}

// NewMockHistoryRepository creates a new mock instance.
func NewMockHistoryRepository(ctrl *gomock.Controller) *MockHistoryRepository {
	mock := &MockHistoryRepository{ctrl: ctrl}
	mock.recorder = &MockHistoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHistoryRepository) EXPECT() *MockHistoryRepositoryMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockHistoryRepository) Append(ctx context.Context, history model.History) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", ctx, history)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockHistoryRepositoryMockRecorder) Append(ctx, history any) *MockHistoryRepositoryAppendCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockHistoryRepository)(nil).Append), ctx, history)
	return &MockHistoryRepositoryAppendCall{Call: call}
}

// MockHistoryRepositoryAppendCall wrap *gomock.Call
type MockHistoryRepositoryAppendCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHistoryRepositoryAppendCall) Return(arg0 error) *MockHistoryRepositoryAppendCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHistoryRepositoryAppendCall) Do(f func(context.Context, model.History) error) *MockHistoryRepositoryAppendCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHistoryRepositoryAppendCall) DoAndReturn(f func(context.Context, model.History) error) *MockHistoryRepositoryAppendCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Init mocks base method.
func (m *MockHistoryRepository) Init(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockHistoryRepositoryMockRecorder) Init(ctx any) *MockHistoryRepositoryInitCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockHistoryRepository)(nil).Init), ctx)
	return &MockHistoryRepositoryInitCall{Call: call}
}

// MockHistoryRepositoryInitCall wrap *gomock.Call
type MockHistoryRepositoryInitCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHistoryRepositoryInitCall) Return(arg0 error) *MockHistoryRepositoryInitCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHistoryRepositoryInitCall) Do(f func(context.Context) error) *MockHistoryRepositoryInitCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHistoryRepositoryInitCall) DoAndReturn(f func(context.Context) error) *MockHistoryRepositoryInitCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockHistoryRepository) List(ctx context.Context) (model.Histories, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].(model.Histories)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockHistoryRepositoryMockRecorder) List(ctx any) *MockHistoryRepositoryListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockHistoryRepository)(nil).List), ctx)
	return &MockHistoryRepositoryListCall{Call: call}
}

// MockHistoryRepositoryListCall wrap *gomock.Call
type MockHistoryRepositoryListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHistoryRepositoryListCall) Return(arg0 model.Histories, arg1 error) *MockHistoryRepositoryListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHistoryRepositoryListCall) Do(f func(context.Context) (model.Histories, error)) *MockHistoryRepositoryListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHistoryRepositoryListCall) DoAndReturn(f func(context.Context) (model.Histories, error)) *MockHistoryRepositoryListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
