package e2e

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/nao1215/filesql"
	"github.com/xuri/excelize/v2"
)

// The Excel sheet-visibility contract is asserted by atago specs, which need
// real workbook files. A workbook is a ZIP of XML, so a committed one says
// nothing about itself: a fixture named "hidden.xlsx" could hold no hidden sheet
// at all and every scenario using it would keep passing while proving nothing.
//
// So the fixtures are described here, in Go, and this file does two jobs. It
// writes them (with REGEN_EXCEL_FIXTURES=1), and — on every ordinary test run —
// it reads the committed files back and checks they still hold what they claim.
// The second is the one that matters: it is what stops a fixture drifting away
// from the contract the specs believe it carries.

// fixtureVisibility is how a fixture workbook stores one sheet. Excel separates
// hidden, which a reader can undo from the sheet tabs, from very hidden, which
// only the VBA editor can. sqly does not tell the two apart, and these fixtures
// carry both so that claim is tested rather than assumed.
type fixtureVisibility int

const (
	fixtureVisible fixtureVisibility = iota
	fixtureHidden
	fixtureVeryHidden
)

func (v fixtureVisibility) shown() bool { return v == fixtureVisible }

func (v fixtureVisibility) String() string {
	switch v {
	case fixtureVisible:
		return "visible"
	case fixtureHidden:
		return "hidden"
	case fixtureVeryHidden:
		return "very hidden"
	default:
		return "unknown"
	}
}

// fixtureSheet is one sheet of a fixture workbook: its name, its visibility, and
// the value its single data row carries, which is what a spec queries for.
type fixtureSheet struct {
	name       string
	visibility fixtureVisibility
	value      string
}

// fixtureWorkbook is one generated workbook. The sheets are written in the order
// given, which is the order the specs expect to see them reported in.
type fixtureWorkbook struct {
	path   string
	sheets []fixtureSheet
}

// excelFixtures are the workbooks the visibility specs run against.
var excelFixtures = []fixtureWorkbook{
	{
		// The main mixed workbook: shown, hidden, very hidden, shown again. The
		// trailing shown sheet is what makes "order survives the filter" fail if
		// filtering ever reorders anything.
		path: filepath.Join("atago", "testdata", "sheets_visibility.xlsx"),
		sheets: []fixtureSheet{
			{name: "Visible", visibility: fixtureVisible, value: "shown"},
			{name: "Internal", visibility: fixtureHidden, value: "hidden"},
			{name: "Secret", visibility: fixtureVeryHidden, value: "very-hidden"},
			{name: "Summary", visibility: fixtureVisible, value: "shown-too"},
		},
	},
	{
		// Two sheets that sanitize to one table name, one of them hidden. Under
		// the default policy this workbook loads; with --include-hidden-sheets
		// the same file is refused. Nothing else in the suite pins that the
		// collision check runs after the visibility filter and not before.
		path: filepath.Join("atago", "testdata", "sheets_hidden_collision.xlsx"),
		sheets: []fixtureSheet{
			{name: "Q1 sales", visibility: fixtureVisible, value: "shown"},
			{name: "Q1.sales", visibility: fixtureHidden, value: "hidden"},
		},
	},
}

// TestExcelFixtures_MatchTheirDeclaredVisibility is the check that keeps the
// atago specs meaningful. It reads each committed workbook through the same
// library sqly imports with, so a fixture regenerated by hand, edited in Excel,
// or replaced by a lookalike fails here rather than quietly weakening every
// scenario that uses it.
func TestExcelFixtures_MatchTheirDeclaredVisibility(t *testing.T) {
	t.Parallel()

	for _, workbook := range excelFixtures {
		t.Run(workbook.path, func(t *testing.T) {
			t.Parallel()

			sheets, err := filesql.ExcelSheetsInFile(workbook.path)
			if err != nil {
				t.Fatalf("read %s: %v (run `make e2e-fixtures` to regenerate)", workbook.path, err)
			}
			if len(sheets) != len(workbook.sheets) {
				t.Fatalf("%s holds %d sheets, want %d", workbook.path, len(sheets), len(workbook.sheets))
			}
			for i, want := range workbook.sheets {
				got := sheets[i]
				if got.Name != want.name {
					t.Errorf("%s sheet %d is %q, want %q; the workbook's sheet order changed",
						workbook.path, i, got.Name, want.name)
				}
				if got.Visible != want.visibility.shown() {
					t.Errorf("%s sheet %q reports visible=%t, but the fixture is declared %s",
						workbook.path, want.name, got.Visible, want.visibility)
				}
			}
		})
	}
}

// TestExcelFixtures_Regenerate writes the fixtures. It is a test rather than a
// separate command so it stays compiled and cannot rot beside the declaration it
// reads from; it does nothing unless asked.
//
//	REGEN_EXCEL_FIXTURES=1 go test ./e2e/ -run TestExcelFixtures_Regenerate
func TestExcelFixtures_Regenerate(t *testing.T) {
	if os.Getenv("REGEN_EXCEL_FIXTURES") == "" {
		t.Skip("set REGEN_EXCEL_FIXTURES=1 to rewrite the workbook fixtures")
	}
	for _, workbook := range excelFixtures {
		if err := writeFixtureWorkbook(workbook); err != nil {
			t.Fatalf("write %s: %v", workbook.path, err)
		}
		t.Logf("wrote %s", workbook.path)
	}
}

// writeFixtureWorkbook builds one workbook from its declaration.
//
// The active sheet is moved onto a shown one before anything is hidden: Excel
// requires a workbook to show at least one sheet, and excelize enforces it.
func writeFixtureWorkbook(workbook fixtureWorkbook) (err error) {
	const defaultSheet = "Sheet1"

	f := excelize.NewFile()
	defer func() {
		if closeErr := f.Close(); closeErr != nil && err == nil {
			err = closeErr
		}
	}()

	for _, sheet := range workbook.sheets {
		if sheet.name != defaultSheet {
			if _, err := f.NewSheet(sheet.name); err != nil {
				return err
			}
		}
		if err := f.SetCellValue(sheet.name, "A1", "v"); err != nil {
			return err
		}
		if err := f.SetCellValue(sheet.name, "A2", sheet.value); err != nil {
			return err
		}
	}
	if workbook.sheets[0].name != defaultSheet {
		if err := f.DeleteSheet(defaultSheet); err != nil {
			return err
		}
	}

	for _, sheet := range workbook.sheets {
		if !sheet.visibility.shown() {
			continue
		}
		index, err := f.GetSheetIndex(sheet.name)
		if err != nil {
			return err
		}
		f.SetActiveSheet(index)
		break
	}

	for _, sheet := range workbook.sheets {
		switch sheet.visibility {
		case fixtureVisible:
		case fixtureHidden:
			if err := f.SetSheetVisible(sheet.name, false); err != nil {
				return err
			}
		case fixtureVeryHidden:
			if err := f.SetSheetVisible(sheet.name, false, true); err != nil {
				return err
			}
		}
	}

	return f.SaveAs(workbook.path)
}
