// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"database/sql"
	"github.com/nao1215/sqly/config"
	"github.com/nao1215/sqly/infrastructure/filesql"
	"github.com/nao1215/sqly/infrastructure/memory"
	"github.com/nao1215/sqly/infrastructure/persistence"
	"github.com/nao1215/sqly/interactor"
	"github.com/nao1215/sqly/shell"
)

// Injectors from wire.go:

// NewShell initailize main class of sqly application.
// The return function is the function to close the DB.
func NewShell(args []string) (*shell.Shell, func(), error) {
	arg, err := config.NewArg(args)
	if err != nil {
		return nil, nil, err
	}
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	commandList := shell.NewCommands()
	memoryDB, cleanup, err := config.NewInMemDB()
	if err != nil {
		return nil, nil, err
	}
	sqLite3Repository := memory.NewSQLite3Repository(memoryDB)
	sql := interactor.NewSQL()
	databaseUsecase := interactor.NewSQLite3Interactor(sqLite3Repository, sql)
	historyDB, cleanup2, err := config.NewHistoryDB(configConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	historyRepository := persistence.NewHistoryRepository(historyDB)
	historyUsecase := interactor.NewHistoryInteractor(historyRepository)
	fileSQLAdapter := provideFileSQLAdapter(memoryDB)
	fileSQLUsecase := interactor.NewFileSQLInteractor(fileSQLAdapter)
	csvRepository := persistence.NewCSVRepository()
	tsvRepository := persistence.NewTSVRepository()
	ltsvRepository := persistence.NewLTSVRepository()
	excelRepository := persistence.NewExcelRepository()
	fileRepository := persistence.NewFileRepository()
	exportUsecase := interactor.NewExportInteractor(csvRepository, tsvRepository, ltsvRepository, excelRepository, fileRepository)
	usecases := shell.NewUsecases(databaseUsecase, historyUsecase, fileSQLUsecase, exportUsecase)
	shellShell, err := shell.NewShell(arg, configConfig, commandList, usecases)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return shellShell, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// provideFileSQLAdapter creates a FileSQLAdapter with the shared database
func provideFileSQLAdapter(db config.MemoryDB) *filesql.FileSQLAdapter {
	return filesql.NewFileSQLAdapter((*sql.DB)(db))
}
