// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/nao1215/sqly/config"
	"github.com/nao1215/sqly/infrastructure/memory"
	"github.com/nao1215/sqly/infrastructure/persistence"
	"github.com/nao1215/sqly/interactor"
	"github.com/nao1215/sqly/shell"
)

// Injectors from wire.go:

// NewShell initailize main class of sqly application.
// The return function is the function to close the DB.
func NewShell(args []string) (*shell.Shell, func(), error) {
	arg, err := config.NewArg(args)
	if err != nil {
		return nil, nil, err
	}
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	commandList := shell.NewCommands()
	csvRepository := persistence.NewCSVRepository()
	csvUsecase := interactor.NewCSVInteractor(csvRepository)
	tsvRepository := persistence.NewTSVRepository()
	tsvUsecase := interactor.NewTSVInteractor(tsvRepository)
	ltsvRepository := persistence.NewLTSVRepository()
	ltsvUsecase := interactor.NewLTSVInteractor(ltsvRepository)
	jsonRepository := persistence.NewJSONRepository()
	jsonUsecase := interactor.NewJSONInteractor(jsonRepository)
	memoryDB, cleanup, err := config.NewInMemDB()
	if err != nil {
		return nil, nil, err
	}
	sqLite3Repository := memory.NewSQLite3Repository(memoryDB)
	sql := interactor.NewSQL()
	databaseUsecase := interactor.NewSQLite3Interactor(sqLite3Repository, sql)
	historyDB, cleanup2, err := config.NewHistoryDB(configConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	historyRepository := persistence.NewHistoryRepository(historyDB)
	historyUsecase := interactor.NewHistoryInteractor(historyRepository)
	excelRepository := persistence.NewExcelRepository()
	excelUsecase := interactor.NewExcelInteractor(excelRepository)
	shellShell := shell.NewShell(arg, configConfig, commandList, csvUsecase, tsvUsecase, ltsvUsecase, jsonUsecase, databaseUsecase, historyUsecase, excelUsecase)
	return shellShell, func() {
		cleanup2()
		cleanup()
	}, nil
}
