site_name: "sqly documentation"
theme: "material"

nav:
  - Home: index.md
docs_dir: markdown
plugins:
  - "search"
extra_css:
  - "stylesheets/extra.css"
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
