// Code generated by MockGen. DO NOT EDIT.
// Source: export.go
//
// Generated by this command:
//
//	mockgen -typed -source=export.go -destination=../interactor/mock/export.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	model "github.com/nao1215/sqly/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockExportUsecase is a mock of ExportUsecase interface.
type MockExportUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockExportUsecaseMockRecorder
	isgomock struct{}
}

// MockExportUsecaseMockRecorder is the mock recorder for MockExportUsecase.
type MockExportUsecaseMockRecorder struct {
	mock *MockExportUsecase
}

// NewMockExportUsecase creates a new mock instance.
func NewMockExportUsecase(ctrl *gomock.Controller) *MockExportUsecase {
	mock := &MockExportUsecase{ctrl: ctrl}
	mock.recorder = &MockExportUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExportUsecase) EXPECT() *MockExportUsecaseMockRecorder {
	return m.recorder
}

// DumpTable mocks base method.
func (m *MockExportUsecase) DumpTable(filePath string, table *model.Table, format model.ExportFormat) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DumpTable", filePath, table, format)
	ret0, _ := ret[0].(error)
	return ret0
}

// DumpTable indicates an expected call of DumpTable.
func (mr *MockExportUsecaseMockRecorder) DumpTable(filePath, table, format any) *MockExportUsecaseDumpTableCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DumpTable", reflect.TypeOf((*MockExportUsecase)(nil).DumpTable), filePath, table, format)
	return &MockExportUsecaseDumpTableCall{Call: call}
}

// MockExportUsecaseDumpTableCall wrap *gomock.Call
type MockExportUsecaseDumpTableCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExportUsecaseDumpTableCall) Return(arg0 error) *MockExportUsecaseDumpTableCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExportUsecaseDumpTableCall) Do(f func(string, *model.Table, model.ExportFormat) error) *MockExportUsecaseDumpTableCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExportUsecaseDumpTableCall) DoAndReturn(f func(string, *model.Table, model.ExportFormat) error) *MockExportUsecaseDumpTableCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
