// Code generated by MockGen. DO NOT EDIT.
// Source: history.go
//
// Generated by this command:
//
//	mockgen -typed -source=history.go -destination=../interactor/mock/history.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/nao1215/sqly/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockHistoryUsecase is a mock of HistoryUsecase interface.
type MockHistoryUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockHistoryUsecaseMockRecorder
	isgomock struct{}
}

// MockHistoryUsecaseMockRecorder is the mock recorder for MockHistoryUsecase.
type MockHistoryUsecaseMockRecorder struct {
	mock *MockHistoryUsecase
}

// NewMockHistoryUsecase creates a new mock instance.
func NewMockHistoryUsecase(ctrl *gomock.Controller) *MockHistoryUsecase {
	mock := &MockHistoryUsecase{ctrl: ctrl}
	mock.recorder = &MockHistoryUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHistoryUsecase) EXPECT() *MockHistoryUsecaseMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockHistoryUsecase) Append(ctx context.Context, history model.History) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", ctx, history)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockHistoryUsecaseMockRecorder) Append(ctx, history any) *MockHistoryUsecaseAppendCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockHistoryUsecase)(nil).Append), ctx, history)
	return &MockHistoryUsecaseAppendCall{Call: call}
}

// MockHistoryUsecaseAppendCall wrap *gomock.Call
type MockHistoryUsecaseAppendCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHistoryUsecaseAppendCall) Return(arg0 error) *MockHistoryUsecaseAppendCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHistoryUsecaseAppendCall) Do(f func(context.Context, model.History) error) *MockHistoryUsecaseAppendCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHistoryUsecaseAppendCall) DoAndReturn(f func(context.Context, model.History) error) *MockHistoryUsecaseAppendCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Init mocks base method.
func (m *MockHistoryUsecase) Init(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockHistoryUsecaseMockRecorder) Init(ctx any) *MockHistoryUsecaseInitCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockHistoryUsecase)(nil).Init), ctx)
	return &MockHistoryUsecaseInitCall{Call: call}
}

// MockHistoryUsecaseInitCall wrap *gomock.Call
type MockHistoryUsecaseInitCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHistoryUsecaseInitCall) Return(arg0 error) *MockHistoryUsecaseInitCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHistoryUsecaseInitCall) Do(f func(context.Context) error) *MockHistoryUsecaseInitCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHistoryUsecaseInitCall) DoAndReturn(f func(context.Context) error) *MockHistoryUsecaseInitCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockHistoryUsecase) List(ctx context.Context) (model.Histories, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].(model.Histories)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockHistoryUsecaseMockRecorder) List(ctx any) *MockHistoryUsecaseListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockHistoryUsecase)(nil).List), ctx)
	return &MockHistoryUsecaseListCall{Call: call}
}

// MockHistoryUsecaseListCall wrap *gomock.Call
type MockHistoryUsecaseListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHistoryUsecaseListCall) Return(arg0 model.Histories, arg1 error) *MockHistoryUsecaseListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHistoryUsecaseListCall) Do(f func(context.Context) (model.Histories, error)) *MockHistoryUsecaseListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHistoryUsecaseListCall) DoAndReturn(f func(context.Context) (model.Histories, error)) *MockHistoryUsecaseListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
