// Code generated by MockGen. DO NOT EDIT.
// Source: import.go
//
// Generated by this command:
//
//	mockgen -typed -source=import.go -destination=../interactor/mock/import.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/nao1215/sqly/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockImportUsecase is a mock of ImportUsecase interface.
type MockImportUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockImportUsecaseMockRecorder
	isgomock struct{}
}

// MockImportUsecaseMockRecorder is the mock recorder for MockImportUsecase.
type MockImportUsecaseMockRecorder struct {
	mock *MockImportUsecase
}

// NewMockImportUsecase creates a new mock instance.
func NewMockImportUsecase(ctrl *gomock.Controller) *MockImportUsecase {
	mock := &MockImportUsecase{ctrl: ctrl}
	mock.recorder = &MockImportUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImportUsecase) EXPECT() *MockImportUsecaseMockRecorder {
	return m.recorder
}

// ExcelSheetTableNames mocks base method.
func (m *MockImportUsecase) ExcelSheetTableNames(path string, sheetNames []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExcelSheetTableNames", path, sheetNames)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExcelSheetTableNames indicates an expected call of ExcelSheetTableNames.
func (mr *MockImportUsecaseMockRecorder) ExcelSheetTableNames(path, sheetNames any) *MockImportUsecaseExcelSheetTableNamesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExcelSheetTableNames", reflect.TypeOf((*MockImportUsecase)(nil).ExcelSheetTableNames), path, sheetNames)
	return &MockImportUsecaseExcelSheetTableNamesCall{Call: call}
}

// MockImportUsecaseExcelSheetTableNamesCall wrap *gomock.Call
type MockImportUsecaseExcelSheetTableNamesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockImportUsecaseExcelSheetTableNamesCall) Return(arg0 []string, arg1 error) *MockImportUsecaseExcelSheetTableNamesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockImportUsecaseExcelSheetTableNamesCall) Do(f func(string, []string) ([]string, error)) *MockImportUsecaseExcelSheetTableNamesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockImportUsecaseExcelSheetTableNamesCall) DoAndReturn(f func(string, []string) ([]string, error)) *MockImportUsecaseExcelSheetTableNamesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ExcelSheets mocks base method.
func (m *MockImportUsecase) ExcelSheets(path string) ([]model.ExcelSheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExcelSheets", path)
	ret0, _ := ret[0].([]model.ExcelSheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExcelSheets indicates an expected call of ExcelSheets.
func (mr *MockImportUsecaseMockRecorder) ExcelSheets(path any) *MockImportUsecaseExcelSheetsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExcelSheets", reflect.TypeOf((*MockImportUsecase)(nil).ExcelSheets), path)
	return &MockImportUsecaseExcelSheetsCall{Call: call}
}

// MockImportUsecaseExcelSheetsCall wrap *gomock.Call
type MockImportUsecaseExcelSheetsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockImportUsecaseExcelSheetsCall) Return(arg0 []model.ExcelSheet, arg1 error) *MockImportUsecaseExcelSheetsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockImportUsecaseExcelSheetsCall) Do(f func(string) ([]model.ExcelSheet, error)) *MockImportUsecaseExcelSheetsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockImportUsecaseExcelSheetsCall) DoAndReturn(f func(string) ([]model.ExcelSheet, error)) *MockImportUsecaseExcelSheetsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetTableNameFromFilePath mocks base method.
func (m *MockImportUsecase) GetTableNameFromFilePath(filePath string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTableNameFromFilePath", filePath)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetTableNameFromFilePath indicates an expected call of GetTableNameFromFilePath.
func (mr *MockImportUsecaseMockRecorder) GetTableNameFromFilePath(filePath any) *MockImportUsecaseGetTableNameFromFilePathCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableNameFromFilePath", reflect.TypeOf((*MockImportUsecase)(nil).GetTableNameFromFilePath), filePath)
	return &MockImportUsecaseGetTableNameFromFilePathCall{Call: call}
}

// MockImportUsecaseGetTableNameFromFilePathCall wrap *gomock.Call
type MockImportUsecaseGetTableNameFromFilePathCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockImportUsecaseGetTableNameFromFilePathCall) Return(arg0 string) *MockImportUsecaseGetTableNameFromFilePathCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockImportUsecaseGetTableNameFromFilePathCall) Do(f func(string) string) *MockImportUsecaseGetTableNameFromFilePathCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockImportUsecaseGetTableNameFromFilePathCall) DoAndReturn(f func(string) string) *MockImportUsecaseGetTableNameFromFilePathCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IncludeHiddenSheets mocks base method.
func (m *MockImportUsecase) IncludeHiddenSheets() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncludeHiddenSheets")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IncludeHiddenSheets indicates an expected call of IncludeHiddenSheets.
func (mr *MockImportUsecaseMockRecorder) IncludeHiddenSheets() *MockImportUsecaseIncludeHiddenSheetsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncludeHiddenSheets", reflect.TypeOf((*MockImportUsecase)(nil).IncludeHiddenSheets))
	return &MockImportUsecaseIncludeHiddenSheetsCall{Call: call}
}

// MockImportUsecaseIncludeHiddenSheetsCall wrap *gomock.Call
type MockImportUsecaseIncludeHiddenSheetsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockImportUsecaseIncludeHiddenSheetsCall) Return(arg0 bool) *MockImportUsecaseIncludeHiddenSheetsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockImportUsecaseIncludeHiddenSheetsCall) Do(f func() bool) *MockImportUsecaseIncludeHiddenSheetsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockImportUsecaseIncludeHiddenSheetsCall) DoAndReturn(f func() bool) *MockImportUsecaseIncludeHiddenSheetsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsExcelFile mocks base method.
func (m *MockImportUsecase) IsExcelFile(filePath string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsExcelFile", filePath)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsExcelFile indicates an expected call of IsExcelFile.
func (mr *MockImportUsecaseMockRecorder) IsExcelFile(filePath any) *MockImportUsecaseIsExcelFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsExcelFile", reflect.TypeOf((*MockImportUsecase)(nil).IsExcelFile), filePath)
	return &MockImportUsecaseIsExcelFileCall{Call: call}
}

// MockImportUsecaseIsExcelFileCall wrap *gomock.Call
type MockImportUsecaseIsExcelFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockImportUsecaseIsExcelFileCall) Return(arg0 bool) *MockImportUsecaseIsExcelFileCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockImportUsecaseIsExcelFileCall) Do(f func(string) bool) *MockImportUsecaseIsExcelFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockImportUsecaseIsExcelFileCall) DoAndReturn(f func(string) bool) *MockImportUsecaseIsExcelFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsSupportedFile mocks base method.
func (m *MockImportUsecase) IsSupportedFile(filePath string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSupportedFile", filePath)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSupportedFile indicates an expected call of IsSupportedFile.
func (mr *MockImportUsecaseMockRecorder) IsSupportedFile(filePath any) *MockImportUsecaseIsSupportedFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSupportedFile", reflect.TypeOf((*MockImportUsecase)(nil).IsSupportedFile), filePath)
	return &MockImportUsecaseIsSupportedFileCall{Call: call}
}

// MockImportUsecaseIsSupportedFileCall wrap *gomock.Call
type MockImportUsecaseIsSupportedFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockImportUsecaseIsSupportedFileCall) Return(arg0 bool) *MockImportUsecaseIsSupportedFileCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockImportUsecaseIsSupportedFileCall) Do(f func(string) bool) *MockImportUsecaseIsSupportedFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockImportUsecaseIsSupportedFileCall) DoAndReturn(f func(string) bool) *MockImportUsecaseIsSupportedFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LoadFiles mocks base method.
func (m *MockImportUsecase) LoadFiles(ctx context.Context, filePaths ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range filePaths {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LoadFiles", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadFiles indicates an expected call of LoadFiles.
func (mr *MockImportUsecaseMockRecorder) LoadFiles(ctx any, filePaths ...any) *MockImportUsecaseLoadFilesCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, filePaths...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadFiles", reflect.TypeOf((*MockImportUsecase)(nil).LoadFiles), varargs...)
	return &MockImportUsecaseLoadFilesCall{Call: call}
}

// MockImportUsecaseLoadFilesCall wrap *gomock.Call
type MockImportUsecaseLoadFilesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockImportUsecaseLoadFilesCall) Return(arg0 error) *MockImportUsecaseLoadFilesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockImportUsecaseLoadFilesCall) Do(f func(context.Context, ...string) error) *MockImportUsecaseLoadFilesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockImportUsecaseLoadFilesCall) DoAndReturn(f func(context.Context, ...string) error) *MockImportUsecaseLoadFilesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// QuoteIdentifier mocks base method.
func (m *MockImportUsecase) QuoteIdentifier(identifier string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuoteIdentifier", identifier)
	ret0, _ := ret[0].(string)
	return ret0
}

// QuoteIdentifier indicates an expected call of QuoteIdentifier.
func (mr *MockImportUsecaseMockRecorder) QuoteIdentifier(identifier any) *MockImportUsecaseQuoteIdentifierCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuoteIdentifier", reflect.TypeOf((*MockImportUsecase)(nil).QuoteIdentifier), identifier)
	return &MockImportUsecaseQuoteIdentifierCall{Call: call}
}

// MockImportUsecaseQuoteIdentifierCall wrap *gomock.Call
type MockImportUsecaseQuoteIdentifierCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockImportUsecaseQuoteIdentifierCall) Return(arg0 string) *MockImportUsecaseQuoteIdentifierCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockImportUsecaseQuoteIdentifierCall) Do(f func(string) string) *MockImportUsecaseQuoteIdentifierCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockImportUsecaseQuoteIdentifierCall) DoAndReturn(f func(string) string) *MockImportUsecaseQuoteIdentifierCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetIncludeHiddenSheets mocks base method.
func (m *MockImportUsecase) SetIncludeHiddenSheets(include bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetIncludeHiddenSheets", include)
}

// SetIncludeHiddenSheets indicates an expected call of SetIncludeHiddenSheets.
func (mr *MockImportUsecaseMockRecorder) SetIncludeHiddenSheets(include any) *MockImportUsecaseSetIncludeHiddenSheetsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIncludeHiddenSheets", reflect.TypeOf((*MockImportUsecase)(nil).SetIncludeHiddenSheets), include)
	return &MockImportUsecaseSetIncludeHiddenSheetsCall{Call: call}
}

// MockImportUsecaseSetIncludeHiddenSheetsCall wrap *gomock.Call
type MockImportUsecaseSetIncludeHiddenSheetsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockImportUsecaseSetIncludeHiddenSheetsCall) Return() *MockImportUsecaseSetIncludeHiddenSheetsCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockImportUsecaseSetIncludeHiddenSheetsCall) Do(f func(bool)) *MockImportUsecaseSetIncludeHiddenSheetsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockImportUsecaseSetIncludeHiddenSheetsCall) DoAndReturn(f func(bool)) *MockImportUsecaseSetIncludeHiddenSheetsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetRowMismatchPolicy mocks base method.
func (m *MockImportUsecase) SetRowMismatchPolicy(policy model.RowMismatchPolicy) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRowMismatchPolicy", policy)
}

// SetRowMismatchPolicy indicates an expected call of SetRowMismatchPolicy.
func (mr *MockImportUsecaseMockRecorder) SetRowMismatchPolicy(policy any) *MockImportUsecaseSetRowMismatchPolicyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRowMismatchPolicy", reflect.TypeOf((*MockImportUsecase)(nil).SetRowMismatchPolicy), policy)
	return &MockImportUsecaseSetRowMismatchPolicyCall{Call: call}
}

// MockImportUsecaseSetRowMismatchPolicyCall wrap *gomock.Call
type MockImportUsecaseSetRowMismatchPolicyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockImportUsecaseSetRowMismatchPolicyCall) Return() *MockImportUsecaseSetRowMismatchPolicyCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockImportUsecaseSetRowMismatchPolicyCall) Do(f func(model.RowMismatchPolicy)) *MockImportUsecaseSetRowMismatchPolicyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockImportUsecaseSetRowMismatchPolicyCall) DoAndReturn(f func(model.RowMismatchPolicy)) *MockImportUsecaseSetRowMismatchPolicyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SkippedRows mocks base method.
func (m *MockImportUsecase) SkippedRows(tables []string) []model.SkippedRows {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SkippedRows", tables)
	ret0, _ := ret[0].([]model.SkippedRows)
	return ret0
}

// SkippedRows indicates an expected call of SkippedRows.
func (mr *MockImportUsecaseMockRecorder) SkippedRows(tables any) *MockImportUsecaseSkippedRowsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SkippedRows", reflect.TypeOf((*MockImportUsecase)(nil).SkippedRows), tables)
	return &MockImportUsecaseSkippedRowsCall{Call: call}
}

// MockImportUsecaseSkippedRowsCall wrap *gomock.Call
type MockImportUsecaseSkippedRowsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockImportUsecaseSkippedRowsCall) Return(arg0 []model.SkippedRows) *MockImportUsecaseSkippedRowsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockImportUsecaseSkippedRowsCall) Do(f func([]string) []model.SkippedRows) *MockImportUsecaseSkippedRowsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockImportUsecaseSkippedRowsCall) DoAndReturn(f func([]string) []model.SkippedRows) *MockImportUsecaseSkippedRowsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
