// Code generated by MockGen. DO NOT EDIT.
// Source: import.go
//
// Generated by this command:
//
//	mockgen -typed -source=import.go -destination=../interactor/mock/import.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/nao1215/sqly/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockImportUsecase is a mock of ImportUsecase interface.
type MockImportUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockImportUsecaseMockRecorder
	isgomock struct{}
}

// MockImportUsecaseMockRecorder is the mock recorder for MockImportUsecase.
type MockImportUsecaseMockRecorder struct {
	mock *MockImportUsecase
}

// NewMockImportUsecase creates a new mock instance.
func NewMockImportUsecase(ctrl *gomock.Controller) *MockImportUsecase {
	mock := &MockImportUsecase{ctrl: ctrl}
	mock.recorder = &MockImportUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImportUsecase) EXPECT() *MockImportUsecaseMockRecorder {
	return m.recorder
}

// GetTableNameFromFilePath mocks base method.
func (m *MockImportUsecase) GetTableNameFromFilePath(filePath string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTableNameFromFilePath", filePath)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetTableNameFromFilePath indicates an expected call of GetTableNameFromFilePath.
func (mr *MockImportUsecaseMockRecorder) GetTableNameFromFilePath(filePath any) *MockImportUsecaseGetTableNameFromFilePathCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableNameFromFilePath", reflect.TypeOf((*MockImportUsecase)(nil).GetTableNameFromFilePath), filePath)
	return &MockImportUsecaseGetTableNameFromFilePathCall{Call: call}
}

// MockImportUsecaseGetTableNameFromFilePathCall wrap *gomock.Call
type MockImportUsecaseGetTableNameFromFilePathCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockImportUsecaseGetTableNameFromFilePathCall) Return(arg0 string) *MockImportUsecaseGetTableNameFromFilePathCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockImportUsecaseGetTableNameFromFilePathCall) Do(f func(string) string) *MockImportUsecaseGetTableNameFromFilePathCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockImportUsecaseGetTableNameFromFilePathCall) DoAndReturn(f func(string) string) *MockImportUsecaseGetTableNameFromFilePathCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetTableNames mocks base method.
func (m *MockImportUsecase) GetTableNames(ctx context.Context) ([]*model.Table, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTableNames", ctx)
	ret0, _ := ret[0].([]*model.Table)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTableNames indicates an expected call of GetTableNames.
func (mr *MockImportUsecaseMockRecorder) GetTableNames(ctx any) *MockImportUsecaseGetTableNamesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableNames", reflect.TypeOf((*MockImportUsecase)(nil).GetTableNames), ctx)
	return &MockImportUsecaseGetTableNamesCall{Call: call}
}

// MockImportUsecaseGetTableNamesCall wrap *gomock.Call
type MockImportUsecaseGetTableNamesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockImportUsecaseGetTableNamesCall) Return(arg0 []*model.Table, arg1 error) *MockImportUsecaseGetTableNamesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockImportUsecaseGetTableNamesCall) Do(f func(context.Context) ([]*model.Table, error)) *MockImportUsecaseGetTableNamesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockImportUsecaseGetTableNamesCall) DoAndReturn(f func(context.Context) ([]*model.Table, error)) *MockImportUsecaseGetTableNamesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsExcelFile mocks base method.
func (m *MockImportUsecase) IsExcelFile(filePath string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsExcelFile", filePath)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsExcelFile indicates an expected call of IsExcelFile.
func (mr *MockImportUsecaseMockRecorder) IsExcelFile(filePath any) *MockImportUsecaseIsExcelFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsExcelFile", reflect.TypeOf((*MockImportUsecase)(nil).IsExcelFile), filePath)
	return &MockImportUsecaseIsExcelFileCall{Call: call}
}

// MockImportUsecaseIsExcelFileCall wrap *gomock.Call
type MockImportUsecaseIsExcelFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockImportUsecaseIsExcelFileCall) Return(arg0 bool) *MockImportUsecaseIsExcelFileCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockImportUsecaseIsExcelFileCall) Do(f func(string) bool) *MockImportUsecaseIsExcelFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockImportUsecaseIsExcelFileCall) DoAndReturn(f func(string) bool) *MockImportUsecaseIsExcelFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsSupportedFile mocks base method.
func (m *MockImportUsecase) IsSupportedFile(filePath string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSupportedFile", filePath)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSupportedFile indicates an expected call of IsSupportedFile.
func (mr *MockImportUsecaseMockRecorder) IsSupportedFile(filePath any) *MockImportUsecaseIsSupportedFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSupportedFile", reflect.TypeOf((*MockImportUsecase)(nil).IsSupportedFile), filePath)
	return &MockImportUsecaseIsSupportedFileCall{Call: call}
}

// MockImportUsecaseIsSupportedFileCall wrap *gomock.Call
type MockImportUsecaseIsSupportedFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockImportUsecaseIsSupportedFileCall) Return(arg0 bool) *MockImportUsecaseIsSupportedFileCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockImportUsecaseIsSupportedFileCall) Do(f func(string) bool) *MockImportUsecaseIsSupportedFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockImportUsecaseIsSupportedFileCall) DoAndReturn(f func(string) bool) *MockImportUsecaseIsSupportedFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListExcelSheetNames mocks base method.
func (m *MockImportUsecase) ListExcelSheetNames(filePath string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExcelSheetNames", filePath)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExcelSheetNames indicates an expected call of ListExcelSheetNames.
func (mr *MockImportUsecaseMockRecorder) ListExcelSheetNames(filePath any) *MockImportUsecaseListExcelSheetNamesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExcelSheetNames", reflect.TypeOf((*MockImportUsecase)(nil).ListExcelSheetNames), filePath)
	return &MockImportUsecaseListExcelSheetNamesCall{Call: call}
}

// MockImportUsecaseListExcelSheetNamesCall wrap *gomock.Call
type MockImportUsecaseListExcelSheetNamesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockImportUsecaseListExcelSheetNamesCall) Return(arg0 []string, arg1 error) *MockImportUsecaseListExcelSheetNamesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockImportUsecaseListExcelSheetNamesCall) Do(f func(string) ([]string, error)) *MockImportUsecaseListExcelSheetNamesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockImportUsecaseListExcelSheetNamesCall) DoAndReturn(f func(string) ([]string, error)) *MockImportUsecaseListExcelSheetNamesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LoadFiles mocks base method.
func (m *MockImportUsecase) LoadFiles(ctx context.Context, filePaths ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range filePaths {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LoadFiles", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadFiles indicates an expected call of LoadFiles.
func (mr *MockImportUsecaseMockRecorder) LoadFiles(ctx any, filePaths ...any) *MockImportUsecaseLoadFilesCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, filePaths...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadFiles", reflect.TypeOf((*MockImportUsecase)(nil).LoadFiles), varargs...)
	return &MockImportUsecaseLoadFilesCall{Call: call}
}

// MockImportUsecaseLoadFilesCall wrap *gomock.Call
type MockImportUsecaseLoadFilesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockImportUsecaseLoadFilesCall) Return(arg0 error) *MockImportUsecaseLoadFilesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockImportUsecaseLoadFilesCall) Do(f func(context.Context, ...string) error) *MockImportUsecaseLoadFilesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockImportUsecaseLoadFilesCall) DoAndReturn(f func(context.Context, ...string) error) *MockImportUsecaseLoadFilesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MalformedRowPolicy mocks base method.
func (m *MockImportUsecase) MalformedRowPolicy() model.MalformedRowPolicy {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MalformedRowPolicy")
	ret0, _ := ret[0].(model.MalformedRowPolicy)
	return ret0
}

// MalformedRowPolicy indicates an expected call of MalformedRowPolicy.
func (mr *MockImportUsecaseMockRecorder) MalformedRowPolicy() *MockImportUsecaseMalformedRowPolicyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MalformedRowPolicy", reflect.TypeOf((*MockImportUsecase)(nil).MalformedRowPolicy))
	return &MockImportUsecaseMalformedRowPolicyCall{Call: call}
}

// MockImportUsecaseMalformedRowPolicyCall wrap *gomock.Call
type MockImportUsecaseMalformedRowPolicyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockImportUsecaseMalformedRowPolicyCall) Return(arg0 model.MalformedRowPolicy) *MockImportUsecaseMalformedRowPolicyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockImportUsecaseMalformedRowPolicyCall) Do(f func() model.MalformedRowPolicy) *MockImportUsecaseMalformedRowPolicyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockImportUsecaseMalformedRowPolicyCall) DoAndReturn(f func() model.MalformedRowPolicy) *MockImportUsecaseMalformedRowPolicyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// QuoteIdentifier mocks base method.
func (m *MockImportUsecase) QuoteIdentifier(identifier string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuoteIdentifier", identifier)
	ret0, _ := ret[0].(string)
	return ret0
}

// QuoteIdentifier indicates an expected call of QuoteIdentifier.
func (mr *MockImportUsecaseMockRecorder) QuoteIdentifier(identifier any) *MockImportUsecaseQuoteIdentifierCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuoteIdentifier", reflect.TypeOf((*MockImportUsecase)(nil).QuoteIdentifier), identifier)
	return &MockImportUsecaseQuoteIdentifierCall{Call: call}
}

// MockImportUsecaseQuoteIdentifierCall wrap *gomock.Call
type MockImportUsecaseQuoteIdentifierCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockImportUsecaseQuoteIdentifierCall) Return(arg0 string) *MockImportUsecaseQuoteIdentifierCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockImportUsecaseQuoteIdentifierCall) Do(f func(string) string) *MockImportUsecaseQuoteIdentifierCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockImportUsecaseQuoteIdentifierCall) DoAndReturn(f func(string) string) *MockImportUsecaseQuoteIdentifierCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SanitizeForSQL mocks base method.
func (m *MockImportUsecase) SanitizeForSQL(name string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SanitizeForSQL", name)
	ret0, _ := ret[0].(string)
	return ret0
}

// SanitizeForSQL indicates an expected call of SanitizeForSQL.
func (mr *MockImportUsecaseMockRecorder) SanitizeForSQL(name any) *MockImportUsecaseSanitizeForSQLCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SanitizeForSQL", reflect.TypeOf((*MockImportUsecase)(nil).SanitizeForSQL), name)
	return &MockImportUsecaseSanitizeForSQLCall{Call: call}
}

// MockImportUsecaseSanitizeForSQLCall wrap *gomock.Call
type MockImportUsecaseSanitizeForSQLCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockImportUsecaseSanitizeForSQLCall) Return(arg0 string) *MockImportUsecaseSanitizeForSQLCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockImportUsecaseSanitizeForSQLCall) Do(f func(string) string) *MockImportUsecaseSanitizeForSQLCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockImportUsecaseSanitizeForSQLCall) DoAndReturn(f func(string) string) *MockImportUsecaseSanitizeForSQLCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetMalformedRowPolicy mocks base method.
func (m *MockImportUsecase) SetMalformedRowPolicy(policy model.MalformedRowPolicy) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetMalformedRowPolicy", policy)
}

// SetMalformedRowPolicy indicates an expected call of SetMalformedRowPolicy.
func (mr *MockImportUsecaseMockRecorder) SetMalformedRowPolicy(policy any) *MockImportUsecaseSetMalformedRowPolicyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMalformedRowPolicy", reflect.TypeOf((*MockImportUsecase)(nil).SetMalformedRowPolicy), policy)
	return &MockImportUsecaseSetMalformedRowPolicyCall{Call: call}
}

// MockImportUsecaseSetMalformedRowPolicyCall wrap *gomock.Call
type MockImportUsecaseSetMalformedRowPolicyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockImportUsecaseSetMalformedRowPolicyCall) Return() *MockImportUsecaseSetMalformedRowPolicyCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockImportUsecaseSetMalformedRowPolicyCall) Do(f func(model.MalformedRowPolicy)) *MockImportUsecaseSetMalformedRowPolicyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockImportUsecaseSetMalformedRowPolicyCall) DoAndReturn(f func(model.MalformedRowPolicy)) *MockImportUsecaseSetMalformedRowPolicyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
