// Code generated by MockGen. DO NOT EDIT.
// Source: metadata.go
//
// Generated by this command:
//
//	mockgen -typed -source=metadata.go -destination=../interactor/mock/metadata.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/nao1215/sqly/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockMetadataUsecase is a mock of MetadataUsecase interface.
type MockMetadataUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockMetadataUsecaseMockRecorder
	isgomock struct{}
}

// MockMetadataUsecaseMockRecorder is the mock recorder for MockMetadataUsecase.
type MockMetadataUsecaseMockRecorder struct {
	mock *MockMetadataUsecase
}

// NewMockMetadataUsecase creates a new mock instance.
func NewMockMetadataUsecase(ctrl *gomock.Controller) *MockMetadataUsecase {
	mock := &MockMetadataUsecase{ctrl: ctrl}
	mock.recorder = &MockMetadataUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetadataUsecase) EXPECT() *MockMetadataUsecaseMockRecorder {
	return m.recorder
}

// Header mocks base method.
func (m *MockMetadataUsecase) Header(ctx context.Context, tableName string) (*model.Table, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header", ctx, tableName)
	ret0, _ := ret[0].(*model.Table)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockMetadataUsecaseMockRecorder) Header(ctx, tableName any) *MockMetadataUsecaseHeaderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockMetadataUsecase)(nil).Header), ctx, tableName)
	return &MockMetadataUsecaseHeaderCall{Call: call}
}

// MockMetadataUsecaseHeaderCall wrap *gomock.Call
type MockMetadataUsecaseHeaderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMetadataUsecaseHeaderCall) Return(arg0 *model.Table, arg1 error) *MockMetadataUsecaseHeaderCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMetadataUsecaseHeaderCall) Do(f func(context.Context, string) (*model.Table, error)) *MockMetadataUsecaseHeaderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMetadataUsecaseHeaderCall) DoAndReturn(f func(context.Context, string) (*model.Table, error)) *MockMetadataUsecaseHeaderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockMetadataUsecase) List(ctx context.Context, tableName string) (*model.Table, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, tableName)
	ret0, _ := ret[0].(*model.Table)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMetadataUsecaseMockRecorder) List(ctx, tableName any) *MockMetadataUsecaseListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMetadataUsecase)(nil).List), ctx, tableName)
	return &MockMetadataUsecaseListCall{Call: call}
}

// MockMetadataUsecaseListCall wrap *gomock.Call
type MockMetadataUsecaseListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMetadataUsecaseListCall) Return(arg0 *model.Table, arg1 error) *MockMetadataUsecaseListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMetadataUsecaseListCall) Do(f func(context.Context, string) (*model.Table, error)) *MockMetadataUsecaseListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMetadataUsecaseListCall) DoAndReturn(f func(context.Context, string) (*model.Table, error)) *MockMetadataUsecaseListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SchemaObjects mocks base method.
func (m *MockMetadataUsecase) SchemaObjects(ctx context.Context) ([]*model.Table, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SchemaObjects", ctx)
	ret0, _ := ret[0].([]*model.Table)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SchemaObjects indicates an expected call of SchemaObjects.
func (mr *MockMetadataUsecaseMockRecorder) SchemaObjects(ctx any) *MockMetadataUsecaseSchemaObjectsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SchemaObjects", reflect.TypeOf((*MockMetadataUsecase)(nil).SchemaObjects), ctx)
	return &MockMetadataUsecaseSchemaObjectsCall{Call: call}
}

// MockMetadataUsecaseSchemaObjectsCall wrap *gomock.Call
type MockMetadataUsecaseSchemaObjectsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMetadataUsecaseSchemaObjectsCall) Return(arg0 []*model.Table, arg1 error) *MockMetadataUsecaseSchemaObjectsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMetadataUsecaseSchemaObjectsCall) Do(f func(context.Context) ([]*model.Table, error)) *MockMetadataUsecaseSchemaObjectsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMetadataUsecaseSchemaObjectsCall) DoAndReturn(f func(context.Context) ([]*model.Table, error)) *MockMetadataUsecaseSchemaObjectsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TablesName mocks base method.
func (m *MockMetadataUsecase) TablesName(ctx context.Context) ([]*model.Table, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TablesName", ctx)
	ret0, _ := ret[0].([]*model.Table)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TablesName indicates an expected call of TablesName.
func (mr *MockMetadataUsecaseMockRecorder) TablesName(ctx any) *MockMetadataUsecaseTablesNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TablesName", reflect.TypeOf((*MockMetadataUsecase)(nil).TablesName), ctx)
	return &MockMetadataUsecaseTablesNameCall{Call: call}
}

// MockMetadataUsecaseTablesNameCall wrap *gomock.Call
type MockMetadataUsecaseTablesNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMetadataUsecaseTablesNameCall) Return(arg0 []*model.Table, arg1 error) *MockMetadataUsecaseTablesNameCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMetadataUsecaseTablesNameCall) Do(f func(context.Context) ([]*model.Table, error)) *MockMetadataUsecaseTablesNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMetadataUsecaseTablesNameCall) DoAndReturn(f func(context.Context) ([]*model.Table, error)) *MockMetadataUsecaseTablesNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
