// Code generated by MockGen. DO NOT EDIT.
// Source: persistence.go
//
// Generated by this command:
//
//	mockgen -typed -source=persistence.go -destination=../interactor/mock/persistence.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPersistenceUsecase is a mock of PersistenceUsecase interface.
type MockPersistenceUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockPersistenceUsecaseMockRecorder
	isgomock struct{}
}

// MockPersistenceUsecaseMockRecorder is the mock recorder for MockPersistenceUsecase.
type MockPersistenceUsecaseMockRecorder struct {
	mock *MockPersistenceUsecase
}

// NewMockPersistenceUsecase creates a new mock instance.
func NewMockPersistenceUsecase(ctrl *gomock.Controller) *MockPersistenceUsecase {
	mock := &MockPersistenceUsecase{ctrl: ctrl}
	mock.recorder = &MockPersistenceUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersistenceUsecase) EXPECT() *MockPersistenceUsecaseMockRecorder {
	return m.recorder
}

// DumpACHFile mocks base method.
func (m *MockPersistenceUsecase) DumpACHFile(ctx context.Context, baseName, outputPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DumpACHFile", ctx, baseName, outputPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// DumpACHFile indicates an expected call of DumpACHFile.
func (mr *MockPersistenceUsecaseMockRecorder) DumpACHFile(ctx, baseName, outputPath any) *MockPersistenceUsecaseDumpACHFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DumpACHFile", reflect.TypeOf((*MockPersistenceUsecase)(nil).DumpACHFile), ctx, baseName, outputPath)
	return &MockPersistenceUsecaseDumpACHFileCall{Call: call}
}

// MockPersistenceUsecaseDumpACHFileCall wrap *gomock.Call
type MockPersistenceUsecaseDumpACHFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPersistenceUsecaseDumpACHFileCall) Return(arg0 error) *MockPersistenceUsecaseDumpACHFileCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPersistenceUsecaseDumpACHFileCall) Do(f func(context.Context, string, string) error) *MockPersistenceUsecaseDumpACHFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPersistenceUsecaseDumpACHFileCall) DoAndReturn(f func(context.Context, string, string) error) *MockPersistenceUsecaseDumpACHFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DumpFedWireFile mocks base method.
func (m *MockPersistenceUsecase) DumpFedWireFile(ctx context.Context, baseName, outputPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DumpFedWireFile", ctx, baseName, outputPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// DumpFedWireFile indicates an expected call of DumpFedWireFile.
func (mr *MockPersistenceUsecaseMockRecorder) DumpFedWireFile(ctx, baseName, outputPath any) *MockPersistenceUsecaseDumpFedWireFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DumpFedWireFile", reflect.TypeOf((*MockPersistenceUsecase)(nil).DumpFedWireFile), ctx, baseName, outputPath)
	return &MockPersistenceUsecaseDumpFedWireFileCall{Call: call}
}

// MockPersistenceUsecaseDumpFedWireFileCall wrap *gomock.Call
type MockPersistenceUsecaseDumpFedWireFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPersistenceUsecaseDumpFedWireFileCall) Return(arg0 error) *MockPersistenceUsecaseDumpFedWireFileCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPersistenceUsecaseDumpFedWireFileCall) Do(f func(context.Context, string, string) error) *MockPersistenceUsecaseDumpFedWireFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPersistenceUsecaseDumpFedWireFileCall) DoAndReturn(f func(context.Context, string, string) error) *MockPersistenceUsecaseDumpFedWireFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
