// Code generated by MockGen. DO NOT EDIT.
// Source: query.go
//
// Generated by this command:
//
//	mockgen -typed -source=query.go -destination=../interactor/mock/query.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/nao1215/sqly/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockQueryUsecase is a mock of QueryUsecase interface.
type MockQueryUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockQueryUsecaseMockRecorder
	isgomock struct{}
}

// MockQueryUsecaseMockRecorder is the mock recorder for MockQueryUsecase.
type MockQueryUsecaseMockRecorder struct {
	mock *MockQueryUsecase
}

// NewMockQueryUsecase creates a new mock instance.
func NewMockQueryUsecase(ctrl *gomock.Controller) *MockQueryUsecase {
	mock := &MockQueryUsecase{ctrl: ctrl}
	mock.recorder = &MockQueryUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryUsecase) EXPECT() *MockQueryUsecaseMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockQueryUsecase) Exec(ctx context.Context, statement string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", ctx, statement)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockQueryUsecaseMockRecorder) Exec(ctx, statement any) *MockQueryUsecaseExecCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockQueryUsecase)(nil).Exec), ctx, statement)
	return &MockQueryUsecaseExecCall{Call: call}
}

// MockQueryUsecaseExecCall wrap *gomock.Call
type MockQueryUsecaseExecCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQueryUsecaseExecCall) Return(arg0 int64, arg1 error) *MockQueryUsecaseExecCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQueryUsecaseExecCall) Do(f func(context.Context, string) (int64, error)) *MockQueryUsecaseExecCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQueryUsecaseExecCall) DoAndReturn(f func(context.Context, string) (int64, error)) *MockQueryUsecaseExecCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ExecSQL mocks base method.
func (m *MockQueryUsecase) ExecSQL(ctx context.Context, statement string) (*model.Table, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecSQL", ctx, statement)
	ret0, _ := ret[0].(*model.Table)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ExecSQL indicates an expected call of ExecSQL.
func (mr *MockQueryUsecaseMockRecorder) ExecSQL(ctx, statement any) *MockQueryUsecaseExecSQLCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecSQL", reflect.TypeOf((*MockQueryUsecase)(nil).ExecSQL), ctx, statement)
	return &MockQueryUsecaseExecSQLCall{Call: call}
}

// MockQueryUsecaseExecSQLCall wrap *gomock.Call
type MockQueryUsecaseExecSQLCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQueryUsecaseExecSQLCall) Return(arg0 *model.Table, arg1 int64, arg2 error) *MockQueryUsecaseExecSQLCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQueryUsecaseExecSQLCall) Do(f func(context.Context, string) (*model.Table, int64, error)) *MockQueryUsecaseExecSQLCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQueryUsecaseExecSQLCall) DoAndReturn(f func(context.Context, string) (*model.Table, int64, error)) *MockQueryUsecaseExecSQLCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Query mocks base method.
func (m *MockQueryUsecase) Query(ctx context.Context, query string) (*model.Table, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, query)
	ret0, _ := ret[0].(*model.Table)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockQueryUsecaseMockRecorder) Query(ctx, query any) *MockQueryUsecaseQueryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockQueryUsecase)(nil).Query), ctx, query)
	return &MockQueryUsecaseQueryCall{Call: call}
}

// MockQueryUsecaseQueryCall wrap *gomock.Call
type MockQueryUsecaseQueryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQueryUsecaseQueryCall) Return(arg0 *model.Table, arg1 error) *MockQueryUsecaseQueryCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQueryUsecaseQueryCall) Do(f func(context.Context, string) (*model.Table, error)) *MockQueryUsecaseQueryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQueryUsecaseQueryCall) DoAndReturn(f func(context.Context, string) (*model.Table, error)) *MockQueryUsecaseQueryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// QueryStream mocks base method.
func (m *MockQueryUsecase) QueryStream(ctx context.Context, query string, fn func([]string, []bool) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryStream", ctx, query, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueryStream indicates an expected call of QueryStream.
func (mr *MockQueryUsecaseMockRecorder) QueryStream(ctx, query, fn any) *MockQueryUsecaseQueryStreamCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryStream", reflect.TypeOf((*MockQueryUsecase)(nil).QueryStream), ctx, query, fn)
	return &MockQueryUsecaseQueryStreamCall{Call: call}
}

// MockQueryUsecaseQueryStreamCall wrap *gomock.Call
type MockQueryUsecaseQueryStreamCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQueryUsecaseQueryStreamCall) Return(arg0 error) *MockQueryUsecaseQueryStreamCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQueryUsecaseQueryStreamCall) Do(f func(context.Context, string, func([]string, []bool) error) error) *MockQueryUsecaseQueryStreamCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQueryUsecaseQueryStreamCall) DoAndReturn(f func(context.Context, string, func([]string, []bool) error) error) *MockQueryUsecaseQueryStreamCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
