// Code generated by MockGen. DO NOT EDIT.
// Source: sqlite3.go
//
// Generated by this command:
//
//	mockgen -typed -source=sqlite3.go -destination=../interactor/mock/sqlite3.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/nao1215/sqly/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockDatabaseUsecase is a mock of DatabaseUsecase interface.
type MockDatabaseUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseUsecaseMockRecorder
	isgomock struct{}
}

// MockDatabaseUsecaseMockRecorder is the mock recorder for MockDatabaseUsecase.
type MockDatabaseUsecaseMockRecorder struct {
	mock *MockDatabaseUsecase
}

// NewMockDatabaseUsecase creates a new mock instance.
func NewMockDatabaseUsecase(ctrl *gomock.Controller) *MockDatabaseUsecase {
	mock := &MockDatabaseUsecase{ctrl: ctrl}
	mock.recorder = &MockDatabaseUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabaseUsecase) EXPECT() *MockDatabaseUsecaseMockRecorder {
	return m.recorder
}

// CreateTable mocks base method.
func (m *MockDatabaseUsecase) CreateTable(ctx context.Context, t *model.Table) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTable", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTable indicates an expected call of CreateTable.
func (mr *MockDatabaseUsecaseMockRecorder) CreateTable(ctx, t any) *MockDatabaseUsecaseCreateTableCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTable", reflect.TypeOf((*MockDatabaseUsecase)(nil).CreateTable), ctx, t)
	return &MockDatabaseUsecaseCreateTableCall{Call: call}
}

// MockDatabaseUsecaseCreateTableCall wrap *gomock.Call
type MockDatabaseUsecaseCreateTableCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDatabaseUsecaseCreateTableCall) Return(arg0 error) *MockDatabaseUsecaseCreateTableCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDatabaseUsecaseCreateTableCall) Do(f func(context.Context, *model.Table) error) *MockDatabaseUsecaseCreateTableCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDatabaseUsecaseCreateTableCall) DoAndReturn(f func(context.Context, *model.Table) error) *MockDatabaseUsecaseCreateTableCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Exec mocks base method.
func (m *MockDatabaseUsecase) Exec(ctx context.Context, statement string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", ctx, statement)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockDatabaseUsecaseMockRecorder) Exec(ctx, statement any) *MockDatabaseUsecaseExecCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockDatabaseUsecase)(nil).Exec), ctx, statement)
	return &MockDatabaseUsecaseExecCall{Call: call}
}

// MockDatabaseUsecaseExecCall wrap *gomock.Call
type MockDatabaseUsecaseExecCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDatabaseUsecaseExecCall) Return(arg0 int64, arg1 error) *MockDatabaseUsecaseExecCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDatabaseUsecaseExecCall) Do(f func(context.Context, string) (int64, error)) *MockDatabaseUsecaseExecCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDatabaseUsecaseExecCall) DoAndReturn(f func(context.Context, string) (int64, error)) *MockDatabaseUsecaseExecCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ExecSQL mocks base method.
func (m *MockDatabaseUsecase) ExecSQL(ctx context.Context, statement string) (*model.Table, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecSQL", ctx, statement)
	ret0, _ := ret[0].(*model.Table)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ExecSQL indicates an expected call of ExecSQL.
func (mr *MockDatabaseUsecaseMockRecorder) ExecSQL(ctx, statement any) *MockDatabaseUsecaseExecSQLCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecSQL", reflect.TypeOf((*MockDatabaseUsecase)(nil).ExecSQL), ctx, statement)
	return &MockDatabaseUsecaseExecSQLCall{Call: call}
}

// MockDatabaseUsecaseExecSQLCall wrap *gomock.Call
type MockDatabaseUsecaseExecSQLCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDatabaseUsecaseExecSQLCall) Return(arg0 *model.Table, arg1 int64, arg2 error) *MockDatabaseUsecaseExecSQLCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDatabaseUsecaseExecSQLCall) Do(f func(context.Context, string) (*model.Table, int64, error)) *MockDatabaseUsecaseExecSQLCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDatabaseUsecaseExecSQLCall) DoAndReturn(f func(context.Context, string) (*model.Table, int64, error)) *MockDatabaseUsecaseExecSQLCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetTableNameFromFilePath mocks base method.
func (m *MockDatabaseUsecase) GetTableNameFromFilePath(filePath string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTableNameFromFilePath", filePath)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetTableNameFromFilePath indicates an expected call of GetTableNameFromFilePath.
func (mr *MockDatabaseUsecaseMockRecorder) GetTableNameFromFilePath(filePath any) *MockDatabaseUsecaseGetTableNameFromFilePathCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableNameFromFilePath", reflect.TypeOf((*MockDatabaseUsecase)(nil).GetTableNameFromFilePath), filePath)
	return &MockDatabaseUsecaseGetTableNameFromFilePathCall{Call: call}
}

// MockDatabaseUsecaseGetTableNameFromFilePathCall wrap *gomock.Call
type MockDatabaseUsecaseGetTableNameFromFilePathCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDatabaseUsecaseGetTableNameFromFilePathCall) Return(arg0 string) *MockDatabaseUsecaseGetTableNameFromFilePathCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDatabaseUsecaseGetTableNameFromFilePathCall) Do(f func(string) string) *MockDatabaseUsecaseGetTableNameFromFilePathCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDatabaseUsecaseGetTableNameFromFilePathCall) DoAndReturn(f func(string) string) *MockDatabaseUsecaseGetTableNameFromFilePathCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetTableNames mocks base method.
func (m *MockDatabaseUsecase) GetTableNames(ctx context.Context) ([]*model.Table, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTableNames", ctx)
	ret0, _ := ret[0].([]*model.Table)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTableNames indicates an expected call of GetTableNames.
func (mr *MockDatabaseUsecaseMockRecorder) GetTableNames(ctx any) *MockDatabaseUsecaseGetTableNamesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableNames", reflect.TypeOf((*MockDatabaseUsecase)(nil).GetTableNames), ctx)
	return &MockDatabaseUsecaseGetTableNamesCall{Call: call}
}

// MockDatabaseUsecaseGetTableNamesCall wrap *gomock.Call
type MockDatabaseUsecaseGetTableNamesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDatabaseUsecaseGetTableNamesCall) Return(arg0 []*model.Table, arg1 error) *MockDatabaseUsecaseGetTableNamesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDatabaseUsecaseGetTableNamesCall) Do(f func(context.Context) ([]*model.Table, error)) *MockDatabaseUsecaseGetTableNamesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDatabaseUsecaseGetTableNamesCall) DoAndReturn(f func(context.Context) ([]*model.Table, error)) *MockDatabaseUsecaseGetTableNamesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Header mocks base method.
func (m *MockDatabaseUsecase) Header(ctx context.Context, tableName string) (*model.Table, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header", ctx, tableName)
	ret0, _ := ret[0].(*model.Table)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockDatabaseUsecaseMockRecorder) Header(ctx, tableName any) *MockDatabaseUsecaseHeaderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockDatabaseUsecase)(nil).Header), ctx, tableName)
	return &MockDatabaseUsecaseHeaderCall{Call: call}
}

// MockDatabaseUsecaseHeaderCall wrap *gomock.Call
type MockDatabaseUsecaseHeaderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDatabaseUsecaseHeaderCall) Return(arg0 *model.Table, arg1 error) *MockDatabaseUsecaseHeaderCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDatabaseUsecaseHeaderCall) Do(f func(context.Context, string) (*model.Table, error)) *MockDatabaseUsecaseHeaderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDatabaseUsecaseHeaderCall) DoAndReturn(f func(context.Context, string) (*model.Table, error)) *MockDatabaseUsecaseHeaderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Insert mocks base method.
func (m *MockDatabaseUsecase) Insert(ctx context.Context, t *model.Table) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockDatabaseUsecaseMockRecorder) Insert(ctx, t any) *MockDatabaseUsecaseInsertCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockDatabaseUsecase)(nil).Insert), ctx, t)
	return &MockDatabaseUsecaseInsertCall{Call: call}
}

// MockDatabaseUsecaseInsertCall wrap *gomock.Call
type MockDatabaseUsecaseInsertCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDatabaseUsecaseInsertCall) Return(arg0 error) *MockDatabaseUsecaseInsertCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDatabaseUsecaseInsertCall) Do(f func(context.Context, *model.Table) error) *MockDatabaseUsecaseInsertCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDatabaseUsecaseInsertCall) DoAndReturn(f func(context.Context, *model.Table) error) *MockDatabaseUsecaseInsertCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsACHTable mocks base method.
func (m *MockDatabaseUsecase) IsACHTable(tableName string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsACHTable", tableName)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsACHTable indicates an expected call of IsACHTable.
func (mr *MockDatabaseUsecaseMockRecorder) IsACHTable(tableName any) *MockDatabaseUsecaseIsACHTableCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsACHTable", reflect.TypeOf((*MockDatabaseUsecase)(nil).IsACHTable), tableName)
	return &MockDatabaseUsecaseIsACHTableCall{Call: call}
}

// MockDatabaseUsecaseIsACHTableCall wrap *gomock.Call
type MockDatabaseUsecaseIsACHTableCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDatabaseUsecaseIsACHTableCall) Return(arg0 bool) *MockDatabaseUsecaseIsACHTableCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDatabaseUsecaseIsACHTableCall) Do(f func(string) bool) *MockDatabaseUsecaseIsACHTableCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDatabaseUsecaseIsACHTableCall) DoAndReturn(f func(string) bool) *MockDatabaseUsecaseIsACHTableCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsExcelFile mocks base method.
func (m *MockDatabaseUsecase) IsExcelFile(filePath string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsExcelFile", filePath)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsExcelFile indicates an expected call of IsExcelFile.
func (mr *MockDatabaseUsecaseMockRecorder) IsExcelFile(filePath any) *MockDatabaseUsecaseIsExcelFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsExcelFile", reflect.TypeOf((*MockDatabaseUsecase)(nil).IsExcelFile), filePath)
	return &MockDatabaseUsecaseIsExcelFileCall{Call: call}
}

// MockDatabaseUsecaseIsExcelFileCall wrap *gomock.Call
type MockDatabaseUsecaseIsExcelFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDatabaseUsecaseIsExcelFileCall) Return(arg0 bool) *MockDatabaseUsecaseIsExcelFileCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDatabaseUsecaseIsExcelFileCall) Do(f func(string) bool) *MockDatabaseUsecaseIsExcelFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDatabaseUsecaseIsExcelFileCall) DoAndReturn(f func(string) bool) *MockDatabaseUsecaseIsExcelFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsSupportedFile mocks base method.
func (m *MockDatabaseUsecase) IsSupportedFile(filePath string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSupportedFile", filePath)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSupportedFile indicates an expected call of IsSupportedFile.
func (mr *MockDatabaseUsecaseMockRecorder) IsSupportedFile(filePath any) *MockDatabaseUsecaseIsSupportedFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSupportedFile", reflect.TypeOf((*MockDatabaseUsecase)(nil).IsSupportedFile), filePath)
	return &MockDatabaseUsecaseIsSupportedFileCall{Call: call}
}

// MockDatabaseUsecaseIsSupportedFileCall wrap *gomock.Call
type MockDatabaseUsecaseIsSupportedFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDatabaseUsecaseIsSupportedFileCall) Return(arg0 bool) *MockDatabaseUsecaseIsSupportedFileCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDatabaseUsecaseIsSupportedFileCall) Do(f func(string) bool) *MockDatabaseUsecaseIsSupportedFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDatabaseUsecaseIsSupportedFileCall) DoAndReturn(f func(string) bool) *MockDatabaseUsecaseIsSupportedFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsWireTable mocks base method.
func (m *MockDatabaseUsecase) IsWireTable(tableName string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsWireTable", tableName)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsWireTable indicates an expected call of IsWireTable.
func (mr *MockDatabaseUsecaseMockRecorder) IsWireTable(tableName any) *MockDatabaseUsecaseIsWireTableCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsWireTable", reflect.TypeOf((*MockDatabaseUsecase)(nil).IsWireTable), tableName)
	return &MockDatabaseUsecaseIsWireTableCall{Call: call}
}

// MockDatabaseUsecaseIsWireTableCall wrap *gomock.Call
type MockDatabaseUsecaseIsWireTableCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDatabaseUsecaseIsWireTableCall) Return(arg0 bool) *MockDatabaseUsecaseIsWireTableCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDatabaseUsecaseIsWireTableCall) Do(f func(string) bool) *MockDatabaseUsecaseIsWireTableCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDatabaseUsecaseIsWireTableCall) DoAndReturn(f func(string) bool) *MockDatabaseUsecaseIsWireTableCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockDatabaseUsecase) List(ctx context.Context, tableName string) (*model.Table, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, tableName)
	ret0, _ := ret[0].(*model.Table)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockDatabaseUsecaseMockRecorder) List(ctx, tableName any) *MockDatabaseUsecaseListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDatabaseUsecase)(nil).List), ctx, tableName)
	return &MockDatabaseUsecaseListCall{Call: call}
}

// MockDatabaseUsecaseListCall wrap *gomock.Call
type MockDatabaseUsecaseListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDatabaseUsecaseListCall) Return(arg0 *model.Table, arg1 error) *MockDatabaseUsecaseListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDatabaseUsecaseListCall) Do(f func(context.Context, string) (*model.Table, error)) *MockDatabaseUsecaseListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDatabaseUsecaseListCall) DoAndReturn(f func(context.Context, string) (*model.Table, error)) *MockDatabaseUsecaseListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LoadFiles mocks base method.
func (m *MockDatabaseUsecase) LoadFiles(ctx context.Context, filePaths ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range filePaths {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LoadFiles", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadFiles indicates an expected call of LoadFiles.
func (mr *MockDatabaseUsecaseMockRecorder) LoadFiles(ctx any, filePaths ...any) *MockDatabaseUsecaseLoadFilesCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, filePaths...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadFiles", reflect.TypeOf((*MockDatabaseUsecase)(nil).LoadFiles), varargs...)
	return &MockDatabaseUsecaseLoadFilesCall{Call: call}
}

// MockDatabaseUsecaseLoadFilesCall wrap *gomock.Call
type MockDatabaseUsecaseLoadFilesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDatabaseUsecaseLoadFilesCall) Return(arg0 error) *MockDatabaseUsecaseLoadFilesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDatabaseUsecaseLoadFilesCall) Do(f func(context.Context, ...string) error) *MockDatabaseUsecaseLoadFilesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDatabaseUsecaseLoadFilesCall) DoAndReturn(f func(context.Context, ...string) error) *MockDatabaseUsecaseLoadFilesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Query mocks base method.
func (m *MockDatabaseUsecase) Query(ctx context.Context, query string) (*model.Table, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, query)
	ret0, _ := ret[0].(*model.Table)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockDatabaseUsecaseMockRecorder) Query(ctx, query any) *MockDatabaseUsecaseQueryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockDatabaseUsecase)(nil).Query), ctx, query)
	return &MockDatabaseUsecaseQueryCall{Call: call}
}

// MockDatabaseUsecaseQueryCall wrap *gomock.Call
type MockDatabaseUsecaseQueryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDatabaseUsecaseQueryCall) Return(arg0 *model.Table, arg1 error) *MockDatabaseUsecaseQueryCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDatabaseUsecaseQueryCall) Do(f func(context.Context, string) (*model.Table, error)) *MockDatabaseUsecaseQueryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDatabaseUsecaseQueryCall) DoAndReturn(f func(context.Context, string) (*model.Table, error)) *MockDatabaseUsecaseQueryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// QuoteIdentifier mocks base method.
func (m *MockDatabaseUsecase) QuoteIdentifier(identifier string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuoteIdentifier", identifier)
	ret0, _ := ret[0].(string)
	return ret0
}

// QuoteIdentifier indicates an expected call of QuoteIdentifier.
func (mr *MockDatabaseUsecaseMockRecorder) QuoteIdentifier(identifier any) *MockDatabaseUsecaseQuoteIdentifierCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuoteIdentifier", reflect.TypeOf((*MockDatabaseUsecase)(nil).QuoteIdentifier), identifier)
	return &MockDatabaseUsecaseQuoteIdentifierCall{Call: call}
}

// MockDatabaseUsecaseQuoteIdentifierCall wrap *gomock.Call
type MockDatabaseUsecaseQuoteIdentifierCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDatabaseUsecaseQuoteIdentifierCall) Return(arg0 string) *MockDatabaseUsecaseQuoteIdentifierCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDatabaseUsecaseQuoteIdentifierCall) Do(f func(string) string) *MockDatabaseUsecaseQuoteIdentifierCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDatabaseUsecaseQuoteIdentifierCall) DoAndReturn(f func(string) string) *MockDatabaseUsecaseQuoteIdentifierCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SanitizeForSQL mocks base method.
func (m *MockDatabaseUsecase) SanitizeForSQL(name string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SanitizeForSQL", name)
	ret0, _ := ret[0].(string)
	return ret0
}

// SanitizeForSQL indicates an expected call of SanitizeForSQL.
func (mr *MockDatabaseUsecaseMockRecorder) SanitizeForSQL(name any) *MockDatabaseUsecaseSanitizeForSQLCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SanitizeForSQL", reflect.TypeOf((*MockDatabaseUsecase)(nil).SanitizeForSQL), name)
	return &MockDatabaseUsecaseSanitizeForSQLCall{Call: call}
}

// MockDatabaseUsecaseSanitizeForSQLCall wrap *gomock.Call
type MockDatabaseUsecaseSanitizeForSQLCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDatabaseUsecaseSanitizeForSQLCall) Return(arg0 string) *MockDatabaseUsecaseSanitizeForSQLCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDatabaseUsecaseSanitizeForSQLCall) Do(f func(string) string) *MockDatabaseUsecaseSanitizeForSQLCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDatabaseUsecaseSanitizeForSQLCall) DoAndReturn(f func(string) string) *MockDatabaseUsecaseSanitizeForSQLCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TablesName mocks base method.
func (m *MockDatabaseUsecase) TablesName(ctx context.Context) ([]*model.Table, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TablesName", ctx)
	ret0, _ := ret[0].([]*model.Table)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TablesName indicates an expected call of TablesName.
func (mr *MockDatabaseUsecaseMockRecorder) TablesName(ctx any) *MockDatabaseUsecaseTablesNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TablesName", reflect.TypeOf((*MockDatabaseUsecase)(nil).TablesName), ctx)
	return &MockDatabaseUsecaseTablesNameCall{Call: call}
}

// MockDatabaseUsecaseTablesNameCall wrap *gomock.Call
type MockDatabaseUsecaseTablesNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDatabaseUsecaseTablesNameCall) Return(arg0 []*model.Table, arg1 error) *MockDatabaseUsecaseTablesNameCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDatabaseUsecaseTablesNameCall) Do(f func(context.Context) ([]*model.Table, error)) *MockDatabaseUsecaseTablesNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDatabaseUsecaseTablesNameCall) DoAndReturn(f func(context.Context) ([]*model.Table, error)) *MockDatabaseUsecaseTablesNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
