name: CheckAutoGenerateFiles

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check_generate_file:
    name: Check auto generate files
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache-dependency-path: "go.sum"

      - name: Install tools
        run: |
          go install go.uber.org/mock/mockgen@latest
      
      - name: check go mod tidy
        run: |
          go mod tidy
          git diff --exit-code

      - name: Check auto generate files
        run: |
          go generate ./...
          git diff --exit-code
